name: rmachinelearning
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - r-caret
